ISOLATE_THRESHOLD: 8
P_VALUE: 0.025
LOCAL_DATA: data/
data_for_netinf_threshold_8.csv: '302844881600'
netinf_network_threshold_8_pval_0.05.csv: '302555400385'
netinf_network_threshold_8_pval_0.025.csv: '307982716543'
