---
title: "donor_summaries"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(NetworkInference)
library(xtable)
library(tidyverse)

result_dir <- '../data/results/'
source('plot_theme.R')

# Load the 2016 diffusion network
load(paste0(result_dir, '2016_output.RData'))
```

## Preprocessing

I include the preprocessing code so you can see what data the results are based on
```{r, results=FALSE, cache=TRUE, message=FALSE}
    year <- 2016
infile <- paste0('../data/EL_', substr(as.character(year), 3, 4), '.csv')
date_low <- as.Date(paste0(as.character(year - 1), '-01-01'))
date_high <- as.Date(paste0(as.character(year + 1), '-01-01'))
## This mirrors the first pre processing step in network_inference.R
df <- read_csv(infile) %>%
    select(Donor_ID, Recip_ID, Amt, Tran_Tp, Recip_Tp, Date, Donor_Tp) %>%
    na.omit() %>%
    mutate(Date = as.Date(Date, '%m/%d/%Y')) %>%
    filter(!is.element(Tran_Tp, c('19', '24A', '24C', '24E', '24F', 
                                  '24N', '29')),
           Amt > 0, Date >= date_low, Date < date_high, Recip_Tp == 'CAND')
donors <- group_by(df, Donor_ID) %>%
    summarize(Donor_Tp = Donor_Tp[1],
              n_records = n())

# Indicators for different donor groups (in the data used for inference and in the network (i.e. being tied to other donors))
din <- unique(c(output$network$origin_node, output$network$destination_node))
diif <- unique(output$data$Donor_ID)
donors$in_inference_data <- is.element(donors$Donor_ID, diif)
donors$in_network <- is.element(donors$Donor_ID, din)
```

## Number of donations by donors

### (a) tied to other nodes in the network, 
```{r, echo=FALSE}
pdat <- filter(donors, in_network)
summary(pdat$n_records)
ggplot(pdat) +
    geom_histogram(aes(n_records), color = "white", bins = 30) + 
    scale_x_log10() +
    plot_theme
```

## (b) included in the netinf calculations but not tied to any other donors, and 

```{r, echo=FALSE}
pdat <- filter(donors, in_inference_data, !in_network)
summary(pdat$n_records)
ggplot(pdat) +
    geom_histogram(aes(n_records), color = "white", bins = 30) + 
    scale_x_log10() +
    plot_theme
```

## (c) excluded from the netinf calculations. 
```{r, echo=FALSE}
pdat <- filter(donors, !in_inference_data)
summary(pdat$n_records)
ggplot(pdat) +
    geom_histogram(aes(n_records), color = "white", bins = 30) + 
    scale_x_log10() +
    plot_theme
```